library(data.table)
library(tidyr)
library(dplyr)

setwd("C:\\Users\\jvoig\\Documents\\Tadepe")

# criando a planilha a partir do que eu copiei e colei do site.
# Para melhorar esse script, eu teria que ser capaz de fazer a raspagem 
# diretamente do R!. Melhorar esse script!

plan_simec <- c("Log",
                "Arquivo obras_upload.csv foi processado com sucesso",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/82/obras_upload.csv",
                "Enviado por: Gabriella Beira",
                "07/12/2017 14:48:32",
                "Arquivo obras_upload.csv apresentou erros durante o processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/81/obras_upload.csv",
                "Enviado por: Gabriella Beira",
                "07/12/2017 14:44:22",
                "Arquivo projects_rua_proj_n_ORIGINAL.csv foi processado com sucesso",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/80/projects_rua_proj_n_ORIGINAL.csv",
                "Enviado por: Breno Fortunato",
                "06/12/2017 08:48:37",
                "Arquivo contact_itajuba_ORIGINAL.csv está sendo processado",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/79/contact_itajuba_ORIGINAL.csv",
                "Enviado por: Breno Fortunato",
                "06/12/2017 08:29:51",
                "Arquivo projects_rua_proj_n_ORIGINAL.csv foi processado com sucesso",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/78/projects_rua_proj_n_ORIGINAL.csv",
                "Enviado por: Breno Fortunato",
                "01/12/2017 11:15:30",
                "Arquivo obras_upload.csv foi processado com sucesso",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/77/obras_upload.csv",
                "Enviado por: Jéssica Voigt",
                "17/11/2017 11:09:27",
                "Arquivo obras_upload.csv apresentou erros durante o processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/76/obras_upload.csv",
                "Enviado por: Jéssica Voigt",
                "17/11/2017 11:05:08",
                "Arquivo teste.csv apresentou erros durante o processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/75/teste.csv",
                "Enviado por: Breno Fortunato",
                "17/11/2017 08:33:11",
                "Arquivo teste.csv apresentou erros durante o processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/74/teste.csv",
                "Enviado por: Breno Fortunato",
                "17/11/2017 08:32:22",
                "Arquivo obras_upload.csv apresentou erros durante o processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/73/obras_upload.csv",
                "Enviado por: Jéssica Voigt",
                "16/11/2017 16:30:48",
                "Arquivo obras_upload.csv apresentou erros durante o processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/72/obras_upload.csv",
                "Enviado por: Gabriella Beira",
                "27/10/2017 16:17:25",
                "Arquivo obras_upload.csv foi processado com sucesso",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/71/obras_upload.csv",
                "Enviado por: Breno Fortunato",
                "18/10/2017 16:47:04",
                "Arquivo obras_upload.csv foi processado com sucesso",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/70/obras_upload.csv",
                "Enviado por: Jéssica Voigt",
                "05/10/2017 16:58:55",
                "Arquivo projects_rua_proj_n_ORIGINAL.csv foi processado com sucesso",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/69/projects_rua_proj_n_ORIGINAL.csv",
                "Enviado por: Thiago",
                "05/10/2017 16:08:05",
                "Arquivo projects_rua_proj_n_TESTE.csv foi processado com sucesso",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/68/projects_rua_proj_n_TESTE.csv",
                "Enviado por: Thiago",
                "05/10/2017 16:05:51",
                "Arquivo obras_upload.csv apresentou erros durante o processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/67/obras_upload.csv",
                "Enviado por: Jéssica Voigt",
                "05/10/2017 15:29:26",
                "Arquivo projects_rua_proj_n_original.csv foi processado com sucesso",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/66/projects_rua_proj_n_original.csv",
                "Enviado por: Thiago",
                "05/10/2017 14:55:29",
                "Arquivo projects_rua_proj_n_TESTE.csv foi processado com sucesso",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/65/projects_rua_proj_n_TESTE.csv",
                "Enviado por: Thiago",
                "05/10/2017 14:54:46",
                "Arquivo projects_rua_proj_n.csv foi processado com sucesso",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/64/projects_rua_proj_n.csv",
                "Enviado por: Thiago",
                "05/10/2017 14:51:33",
                "Arquivo projects_rua_proj_n.csv foi processado com sucesso",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/63/projects_rua_proj_n.csv",
                "Enviado por: Thiago",
                "05/10/2017 14:50:46",
                "Arquivo obras_upload.csv apresentou erros durante o processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/62/obras_upload.csv",
                "Enviado por: Gabriella Beira",
                "02/10/2017 18:30:42",
                "Arquivo ob_up_teste.csv foi processado com sucesso",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/61/ob_up_teste.csv",
                "Enviado por: Thiago",
                "29/09/2017 16:31:58",
                "Arquivo ob_up_teste.csv foi processado com sucesso",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/60/ob_up_teste.csv",
                "Enviado por: Thiago",
                "29/09/2017 16:20:50",
                "Arquivo obras_upload.csv apresentou erros durante o processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/59/obras_upload.csv",
                "Enviado por: Jéssica Voigt",
                "29/09/2017 16:01:45",
                "Arquivo obras_upload.csv apresentou erros durante o processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/58/obras_upload.csv",
                "Enviado por: Jéssica Voigt",
                "29/09/2017 15:57:56",
                "Arquivo obras_upload.csv apresentou erros durante o processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/57/obras_upload.csv",
                "Enviado por: Jéssica Voigt",
                "29/09/2017 15:39:45",
                "Arquivo obras_upload.csv apresentou erros durante o processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/56/obras_upload.csv",
                "Enviado por: Jéssica Voigt",
                "29/09/2017 15:10:54",
                "Arquivo obras_upload.csv apresentou erros durante o processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/55/obras_upload.csv",
                "Enviado por: Jéssica Voigt",
                "29/09/2017 15:08:00",
                "Arquivo obras_upload.csv apresentou erros durante o processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/54/obras_upload.csv",
                "Enviado por: Jéssica Voigt",
                "29/09/2017 15:04:10",
                "Arquivo rua_proj_n_teste.csv foi processado com sucesso",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/53/rua_proj_n_teste.csv",
                "Enviado por: Thiago",
                "19/09/2017 13:53:01",
                "Arquivo rua_proj_n_teste.csv foi processado com sucesso",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/52/rua_proj_n_teste.csv",
                "Enviado por: Thiago",
                "19/09/2017 13:51:08",
                "Arquivo santoandre-utf8.csv foi processado com sucesso",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/51/santoandre-utf8.csv",
                "Enviado por: Thiago",
                "22/08/2017 15:58:29",
                "Arquivo SIMEC_transparenciadeobras_18-08-2017_071658-utf8.csv apresentou erros durante o processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/50/SIMEC_transparenciadeobras_18-08-2017_071658-utf8.csv",
                "Enviado por: Thiago",
                "20/08/2017 11:10:44",
                "Arquivo SIMEC_transparenciadeobras_18-08-2017_071658.csv está sendo processado",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/49/SIMEC_transparenciadeobras_18-08-2017_071658.csv",
                "Enviado por: Jéssica Voigt",
                "18/08/2017 19:34:49",
                "Arquivo obras18082017.csv apresentou erros durante o processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/48/obras18082017.csv",
                "Enviado por: Jéssica Voigt",
                "18/08/2017 19:29:14",
                "Arquivo obras18082017.csv apresentou erros durante o processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/47/obras18082017.csv",
                "Enviado por: Jéssica Voigt",
                "18/08/2017 19:18:29",
                "Arquivo obras18082017.csv apresentou erros durante o processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/46/obras18082017.csv",
                "Enviado por: Jéssica Voigt",
                "18/08/2017 19:03:30",
                "Arquivo sample_obras.csv foi processado com sucesso",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/45/sample_obras.csv",
                "Enviado por: Thiago",
                "25/07/2017 20:29:53",
                "Arquivo sample_obras.csv apresentou erros durante o processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/44/sample_obras.csv",
                "Enviado por: Thiago",
                "25/07/2017 20:27:44",
                "Arquivo sample_obras.csv apresentou erros durante o processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/43/sample_obras.csv",
                "Enviado por: Thiago",
                "25/07/2017 20:25:14",
                "Arquivo obras24072017.csv foi enfileirado para processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/42/obras24072017.csv",
                "Enviado por: Jéssica Voigt",
                "25/07/2017 18:55:55",
                "Arquivo obras24072017.csv está sendo processado",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/41/obras24072017.csv",
                "Enviado por: Jéssica Voigt",
                "25/07/2017 15:41:52",
                "Arquivo obras110720172.csv apresentou erros durante o processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/40/obras110720172.csv",
                "Enviado por: Thiago",
                "11/07/2017 19:52:41",
                "Arquivo 1_obr_sample.csv está sendo processado",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/39/1_obr_sample.csv",
                "Enviado por: Thiago",
                "11/07/2017 19:33:40",
                "Arquivo 1_obr_sample.csv foi processado com sucesso",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/38/1_obr_sample.csv",
                "Enviado por: Thiago",
                "11/07/2017 17:14:03",
                "Arquivo 1_obr_sample.csv apresentou erros durante o processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/37/1_obr_sample.csv",
                "Enviado por: Thiago",
                "11/07/2017 17:12:26",
                "Arquivo 1_obr_sample.csv apresentou erros durante o processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/36/1_obr_sample.csv",
                "Enviado por: Thiago",
                "11/07/2017 17:07:25",
                "Arquivo 1_obr_sample.csv foi processado com sucesso",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/35/1_obr_sample.csv",
                "Enviado por: Thiago",
                "11/07/2017 15:59:52",
                "Arquivo 1_obr_sample.csv apresentou erros durante o processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/34/1_obr_sample.csv",
                "Enviado por: Thiago",
                "11/07/2017 15:58:01",
                "Arquivo 1_obr_sample.csv apresentou erros durante o processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/33/1_obr_sample.csv",
                "Enviado por: Thiago",
                "11/07/2017 13:46:38",
                "Arquivo obras110720172.csv foi enfileirado para processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/32/obras110720172.csv",
                "Enviado por: Jéssica Voigt",
                "11/07/2017 10:56:20",
                "Arquivo 1_obr_sample.csv apresentou erros durante o processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/31/1_obr_sample.csv",
                "Enviado por: Thiago",
                "11/07/2017 10:05:57",
                "Arquivo 1_obr_sample.csv foi processado com sucesso",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/30/1_obr_sample.csv",
                "Enviado por: Thiago",
                "11/07/2017 09:51:56",
                "Arquivo 1_obr_sample.csv está sendo processado",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/29/1_obr_sample.csv",
                "Enviado por: Thiago",
                "11/07/2017 09:33:56",
                "Arquivo obr_sample.csv foi enfileirado para processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/28/obr_sample.csv",
                "Enviado por: Thiago",
                "11/07/2017 09:12:18",
                "Arquivo obr_sample.csv está sendo processado",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/27/obr_sample.csv",
                "Enviado por: Thiago",
                "11/07/2017 08:55:54",
                "Arquivo 1_obr_sample.csv está sendo processado",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/26/1_obr_sample.csv",
                "Enviado por: Thiago",
                "10/07/2017 20:46:37",
                "Arquivo 1_obr_sample.csv está sendo processado",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/25/1_obr_sample.csv",
                "Enviado por: Thiago",
                "10/07/2017 20:44:16",
                "Arquivo obr_sample.csv está sendo processado",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/24/obr_sample.csv",
                "Enviado por: Thiago",
                "10/07/2017 20:33:20",
                "Arquivo 1_obr_sample.csv está sendo processado",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/23/1_obr_sample.csv",
                "Enviado por: Thiago",
                "10/07/2017 20:17:14",
                "Arquivo 1_obr_sample.csv está sendo processado",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/22/1_obr_sample.csv",
                "Enviado por: Thiago",
                "10/07/2017 20:17:05",
                "Arquivo 1_obr_sample.csv está sendo processado",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/21/1_obr_sample.csv",
                "Enviado por: Thiago",
                "10/07/2017 20:03:52",
                "Arquivo 1_obr_sample.csv está sendo processado",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/20/1_obr_sample.csv",
                "Enviado por: Thiago",
                "10/07/2017 19:58:39",
                "Arquivo 1_obr_sample.csv foi enfileirado para processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/19/1_obr_sample.csv",
                "Enviado por: Thiago",
                "10/07/2017 19:13:52",
                "Arquivo 1_obr_sample.csv foi enfileirado para processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/18/1_obr_sample.csv",
                "Enviado por: Thiago",
                "10/07/2017 18:23:19",
                "Arquivo obr_sample.csv foi enfileirado para processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/17/obr_sample.csv",
                "Enviado por: Thiago",
                "10/07/2017 18:13:46",
                "Arquivo 1_obr_sample.csv foi enfileirado para processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/16/1_obr_sample.csv",
                "Enviado por: Thiago",
                "10/07/2017 18:06:44",
                "Arquivo 1_obr_sample.csv foi enfileirado para processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/15/1_obr_sample.csv",
                "Enviado por: Thiago",
                "10/07/2017 17:03:13",
                "Arquivo 1_obr_sample.csv foi enfileirado para processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/14/1_obr_sample.csv",
                "Enviado por: Thiago",
                "10/07/2017 16:51:10",
                "Arquivo 1_obr_sample.csv foi enfileirado para processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/13/1_obr_sample.csv",
                "Enviado por: Thiago",
                "10/07/2017 16:40:20",
                "Arquivo 1_obr_sample.csv foi enfileirado para processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/12/1_obr_sample.csv",
                "Enviado por: Thiago",
                "10/07/2017 16:27:16",
                "Arquivo 1_obr_sample.csv foi enfileirado para processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/11/1_obr_sample.csv",
                "Enviado por: Thiago",
                "10/07/2017 16:10:47",
                "Arquivo 1_obr_sample.csv foi enfileirado para processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/10/1_obr_sample.csv",
                "Enviado por: Thiago",
                "10/07/2017 15:53:46",
                "Arquivo 1_obr_sample.csv foi enfileirado para processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/9/1_obr_sample.csv",
                "Enviado por: Thiago",
                "10/07/2017 15:48:29",
                "Arquivo 1_obr_sample.csv foi enfileirado para processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/8/1_obr_sample.csv",
                "Enviado por: Thiago",
                "10/07/2017 14:56:25",
                "Arquivo 1_obr_sample.csv está sendo processado",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/7/1_obr_sample.csv",
                "Enviado por: Thiago",
                "10/07/2017 13:50:22",
                "Arquivo obr_sample.csv está sendo processado",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/6/obr_sample.csv",
                "Enviado por: Thiago",
                "10/07/2017 12:44:50",
                "Arquivo obras05062017.csv foi enfileirado para processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/5/obras05062017.csv",
                "Enviado por: Thiago",
                "26/06/2017 16:00:55",
                "Arquivo obras05062017.csv foi enfileirado para processamento",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/4/obras05062017.csv",
                "Enviado por: Jéssica Voigt",
                "05/06/2017 11:48:25",
                "Arquivo obras30052017.csv está sendo processado",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/3/obras30052017.csv",
                "Enviado por: Jéssica Voigt",
                "30/05/2017 19:48:38",
                "Arquivo obras060420172.csv",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/2/obras060420172.csv",
                "Enviado por: Jéssica Voigt",
                "10/04/2017 12:24:44",
                "Arquivo obras060420172.csv",
                "URL: https://ta-de-pe.s3.amazonaws.com/upload/project/1/obras060420172.csv",
                "Enviado por: Jéssica Voigt",
                "07/04/2017 15:35:52")

#transformando texto em df

plan_simec  <- read.csv(text = plan_simec , strip.white = TRUE)

#Criando as colunas (spread) e um id (linha 352)

planilhas <- plan_simec %>%
  mutate(status = ifelse(grepl("Enviado por:", Log), "USER",
                         ifelse(grepl("URL:", Log), "URL",
                                ifelse(grepl("Arquivo", Log), "NAME_FILE", "DATE_upload"))),
         Log = as.character(Log),
         id = rep(1:(nrow(planilhas)/4), each = 4)) %>%
  spread(status, Log)

write.table(planilhas, file="planilhas.csv", 
            sep=";", row.names=F, na="", quote = F)
